name: ${project.name}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
authors: [Zyromate, Xanthard]

commands:
  skullwarsportals:
    description: Gives the player a portal remover
    usage: /<command> giveremover <player>
    aliases: [portal, skportals]
  skullwarsportalsreload:
    description: Reloads the plugin
    usage: /<command> reload
    aliases: [swp, skp, portal]

