name: ${project.name}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
authors: [Zyromate, Xanthard]

commands:
  skullwarsportals:
    description: Gives the player a portal remover
    usage: /<command> giveremover <player>
    aliases: [portal, skportals]
    permission: skullwarsportals.giveremover
  skullwarsportalsreload:
    description: Reloads the plugin
    aliases: [swp, skp, portal]
    permission: skullwarsportals.reload
  skportalsremoveall:
     description: Removes all active portals.
     usage: /<command>
     permission: skullwarsportals.deleteallportals


